// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// count_triangle_labels_cpp
List count_triangle_labels_cpp(const IntegerVector& n_nodes, const IntegerVector& ei, const IntegerVector& ej, const IntegerVector& labels, const IntegerVector& label_ids, const bool count_wedges);
RcppExport SEXP _CellEdgeR_count_triangle_labels_cpp(SEXP n_nodesSEXP, SEXP eiSEXP, SEXP ejSEXP, SEXP labelsSEXP, SEXP label_idsSEXP, SEXP count_wedgesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type ei(eiSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type ej(ejSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type label_ids(label_idsSEXP);
    Rcpp::traits::input_parameter< const bool >::type count_wedges(count_wedgesSEXP);
    rcpp_result_gen = Rcpp::wrap(count_triangle_labels_cpp(n_nodes, ei, ej, labels, label_ids, count_wedges));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CellEdgeR_count_triangle_labels_cpp", (DL_FUNC) &_CellEdgeR_count_triangle_labels_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_CellEdgeR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
