# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count triangles by unordered label triplets on an undirected graph.
#'
#' @param n_nodes Number of nodes.
#' @param ei,ej Edge lists (1-based indices; same length).
#' @param labels Integer labels (1..K) for each node.
#' @param label_ids Sequence 1..K (kept for compatibility).
#'
#' @return A list with `keys` (label triplets as strings), `counts`, and `tri_total`
#'   (total number of triangles).
#'
#' @keywords internal
count_triangle_labels_cpp <- function(n_nodes, ei, ej, labels, label_ids, count_wedges) {
    .Call(`_CellEdgeR_count_triangle_labels_cpp`, n_nodes, ei, ej, labels, label_ids, count_wedges)
}

